collector:
  image: bowwow/fluentd-autobuild
  container_name: collector
  environment:
    - "MONGO_HOST=mongo"
    - "constraint:node==swarm-node1"
  ports:
    - "8080:8080"
  volumes:
    - .:/fluentd/etc

  net: "cloud-overlay"

mongo:
  image: mongo
  container_name: mongo
  ports:
    - "27017:27017"
  net: "cloud-overlay"
